/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academyhcalc;

import java.awt.Color;
import static java.lang.Integer.parseInt;

/**
 *
 * @author ThinkPad
 */
public class hoursCalc extends javax.swing.JFrame {

    /**
     * Creates new form hoursCalc
     */
    public hoursCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldSeconds = new javax.swing.JTextField();
        fieldMinutes = new javax.swing.JTextField();
        fieldHours = new javax.swing.JTextField();
        lHours = new javax.swing.JLabel();
        lMinutes = new javax.swing.JLabel();
        lSeconds = new javax.swing.JLabel();
        bCalculate = new javax.swing.JButton();
        labelSUM = new javax.swing.JLabel();
        secondsResult = new javax.swing.JLabel();
        errorB = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fieldSeconds.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldSeconds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSecondsActionPerformed(evt);
            }
        });
        fieldSeconds.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldSecondsKeyReleased(evt);
            }
        });

        fieldMinutes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldMinutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldMinutesActionPerformed(evt);
            }
        });
        fieldMinutes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldMinutesKeyReleased(evt);
            }
        });

        fieldHours.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHoursActionPerformed(evt);
            }
        });
        fieldHours.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldHoursKeyReleased(evt);
            }
        });

        lHours.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lHours.setText("Hours");

        lMinutes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lMinutes.setText("Minutes");

        lSeconds.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lSeconds.setText("Seconds");

        bCalculate.setText("Calculate");
        bCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCalculateActionPerformed(evt);
            }
        });

        labelSUM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSUM.setText("Seconds until Midnight");

        secondsResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        errorB.setForeground(new java.awt.Color(255, 0, 0));
        errorB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jMenu2.setText("Exit");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelSUM, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(secondsResult, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lHours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldHours, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fieldMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fieldSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(errorB, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lHours)
                    .addComponent(lSeconds)
                    .addComponent(lMinutes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldHours, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSUM, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(secondsResult, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldMinutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldMinutesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldMinutesActionPerformed

    private void bCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalculateActionPerformed
        
        this.a = parseInt(this.fieldHours.getText());
        this.b = parseInt(this.fieldMinutes.getText());
        this.c = parseInt(this.fieldSeconds.getText());
        
        this.suma = (this.a * 60 * 60) + (this.b * 60) + this.c;
        
        this.secondsResult.setText(Integer.toString(suma));
    }//GEN-LAST:event_bCalculateActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void fieldHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHoursActionPerformed

    private void fieldSecondsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSecondsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSecondsActionPerformed

    private void fieldSecondsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldSecondsKeyReleased
        this.c = parseInt(this.fieldSeconds.getText());
        if(this.c > 59 || this.c <= 0){
            this.errorB.setText("Insert correct value for hours, between (0 and 59)! " + this.c + " seconds is not correct.");
            
        }else{
            this.errorB.setText("");
        }
    }//GEN-LAST:event_fieldSecondsKeyReleased

    private void fieldMinutesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldMinutesKeyReleased
        this.b = parseInt(this.fieldMinutes.getText());
        if(this.b > 59 || this.b <= 0){
            this.errorB.setText("Insert correct value for hours, between (0 and 59)! " + this.b + " minutes is not correct.");
            
        }else{
            this.errorB.setText("");
        }
    }//GEN-LAST:event_fieldMinutesKeyReleased

    private void fieldHoursKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldHoursKeyReleased
        this.a = parseInt(this.fieldHours.getText());

        if(this.a > 23 || this.a <= 0){
            this.errorB.setText("Insert correct value for hours, between (0 and 23)! " + this.a + " hours is not correct.");         
        }else{
            this.errorB.setText("");
        }
    }//GEN-LAST:event_fieldHoursKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hoursCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hoursCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hoursCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hoursCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hoursCalc().setVisible(true);
            }
        });
    }
    
    private Integer a = 0;
    private Integer b = 0;
    private Integer c = 0;
    private Integer suma = 0;
    private Boolean error = false;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCalculate;
    private javax.swing.JLabel errorB;
    private javax.swing.JTextField fieldHours;
    private javax.swing.JTextField fieldMinutes;
    private javax.swing.JTextField fieldSeconds;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lHours;
    private javax.swing.JLabel lMinutes;
    private javax.swing.JLabel lSeconds;
    private javax.swing.JLabel labelSUM;
    private javax.swing.JLabel secondsResult;
    // End of variables declaration//GEN-END:variables
}
